# Generated by Django 4.1.2 on 2022-10-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="film_director",
            field=models.CharField(blank=True, max_length=255, null=None),
        ),
        migrations.AlterField(
            model_name="film",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
