# Generated by Django 4.1.2 on 2022-10-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main1", "0002_alter_film_film_director_alter_film_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="film",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
