# Generated by Django 4.1.2 on 2022-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main1", "0003_film_created_film_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="film_director",
            field=models.CharField(max_length=200),
        ),
    ]
