# Generated by Django 4.1.2 on 2022-10-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main1", "0004_alter_film_film_director"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="film",
            name="film_director",
        ),
    ]
