# Generated by Django 4.1.2 on 2022-10-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main1", "0005_director_remove_film_film_director"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="film_director",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="main1.director",
            ),
        ),
    ]
