# Generated by Django 4.1.2 on 2022-10-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main1", "0006_film_film_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="film_director",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="director",
                to="main1.director",
            ),
        ),
    ]
