# Generated by Django 4.1.2 on 2022-10-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main1", "0008_alter_film_film_director_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="name",
            new_name="nick",
        ),
    ]
