# Generated by Django 4.1.2 on 2022-10-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main1", "0009_rename_name_comments_nick"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
